### ISSUE TITLE
MySQL errors causing reports to not show up

### ISSUE THREAD

**Issue by nicholasveronico** [MrTigreroux/TigerReports#106]
Hey! I have just updated TigerReports to 5.0.1 and have made all the corresponding config and messages.yml changes. Doing /reports opens the report menu but shows no reports or archived reports, and all the messages and GUI default to the default messages. I have linked my messages.yml below, along with the error.

Thank you in advance!

Errors: https://www.toptal.com/developers/hastebin/tewirowuze.sql

messages.yml: https://www.toptal.com/developers/hastebin/oxixujazuq.less

**Comment by MrTigreroux** [comment]
Hi,
Thank you for reporting the issue.
The new [version 5.0.2](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455141) should fix one error you have: "com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Every derived table must have its own alias".
For the second error you have: "java.sql.SQLException: Invalid utf8mb4 character string: 'ACED00'". I guess you have some special character in your database that isn't standard (utf8mb4). Do you have any idea what character it could be ? Do you have players speaking in chinese for example ?

**Comment by nicholasveronico** [comment]
Thanks! As far as I know, no. This error wasn’t present prior to updating though. Is there anything that could be done about that?

**Comment by MrTigreroux** [comment]
Is it still there with the new version ?

**Comment by nicholasveronico** [comment]
Yes. There is another error now as well: https://www.toptal.com/developers/hastebin/fubovutoji.properties

**Comment by MrTigreroux** [comment]
Could you try the new [version 5.0.3](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455156) please and tell me if the error "java.lang.ClassCastException: class java.lang.Boolean cannot be cast to class java.lang.Integer" is still there. Thank you in advance.

**Comment by nicholasveronico** [comment]
That error is still present in 5.0.4

**Comment by nicholasveronico** [comment]
Of course. Here it is. https://www.toptal.com/developers/hastebin/izafefaray.apache

**Comment by MrTigreroux** [comment]
Ok thank you, could you try to edit your MySQL database: change the column "archived" of "tigerreports_reports" table to `INT(1)`. If you don't know how to do so, you can follow the tutorial [here](https://github.com/MrTigreroux/TigerReports/wiki/Change-type-of-'reporter_uuid'-(or-'reason')-column).
Then the error should disapear.

**Comment by nicholasveronico** [comment]
That worked and brought back all the reports and archived reports in the GUI. Thank you so much.

**Comment by nicholasveronico** [comment]
Apologies. There appears to be another error when a report goes through. The report doesn't save, as it says the configured report limit has been reached even though it hasn't.

Thanks in advance.

https://www.toptal.com/developers/hastebin/xuyepeluso.properties

**Comment by MrTigreroux** [comment]
Ok thank you, the new [version 5.0.5](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455254) should fix that error. Could you test to open a report with advanced data (data displayed with the book on the top right corner of the menu of a report and tell me if information is correctly displayed. Thank you in advance.

**Comment by nicholasveronico** [comment]
It looks like the error is still present in version 5.0.5. 
https://www.toptal.com/developers/hastebin/pivowazezi.sql

**Comment by MrTigreroux** [comment]
Ok, it should be fixed in the new [version 5.0.6](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455270). Let me know if you have other errors like when you open the menu of a report.

**Comment by nicholasveronico** [comment]
That issue was fixed. Thank you.

A new error has appeared when trying to comment on a report:
https://www.toptal.com/developers/hastebin/bonupiweva.properties

**Comment by MrTigreroux** [comment]
Thank you again for your feedback.
The first error should be fixed with the new [version 5.0.7](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455330).
But I can't understand the second error you have. Could you try to download and install again TigerReportsSupports 1.6.5 ?

**Comment by nicholasveronico** [comment]
No problem. Both errors were fixed in version 5.0.8. However, the GUI shows incorrect data for sent and received reports. As well, the Discord status does not seem to update when processing a report or changing its status.

https://imgur.com/a/o521BCl
https://imgur.com/a/X4wZYdQ

**Comment by MrTigreroux** [comment]
Do the statistics are correctly displayed in the menu opened with `/reports user <player>` ?
Do you have any error since the loading of TigerReports and the display of the menu ?

**Comment by nicholasveronico** [comment]
The statistics are also incorrect with /reports user <player>. The only error I am receiving is the invalid character one, which I am still quite confused with, as I cannot find that character through querying reporter_messages and reported_messages. 

For the TigerReportsSupports issue, I have NotifyOnlyLocalReports set to true, but I am logged on that specific server when I send and process the report.

**Comment by MrTigreroux** [comment]
Have you tried the TigerReports 5.0.9 version ? Maybe it will fix the invalid character error.

**Comment by MrTigreroux** [comment]
Have you tried the TigerReports 5.0.9 version ? Maybe it will fix the invalid character error.

For the TigerReportsSupports issue I would need more logs
I would need you to stop your server, download and rename this file: [logs.config.txt](https://github.com/MrTigreroux/TigerReports/files/8645599/logs.config.txt) to "logs.config" and put it in your plugins/TigerReports folder, then start your server, report someone (yourself for example), open the menu of the created report, change its status and then stop your server, and finally send me all the logs starting from "[TigerReports Enabling..." to [TigerReports] Disabling..." (Be careful to remove any IP/private information in those logs, you can send them in private message of SpigotMC if you are not sure).

**Comment by nicholasveronico** [comment]
The invalid character error is still present in 5.0.9.

Here are the logs.

https://mcpaste.io/b80cf4caa57fa725

**Comment by MrTigreroux** [comment]
I think that I finally found where the problem was, thanks to your logs.
It should be fixed in the new [version 5.0.10](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455412).
Please let me know if it's not the case or if you still have issues like the Discord one.

**Comment by nicholasveronico** [comment]
The invalid character error was fixed. Thank you.

The Discord issue is still present. The status of the report is not changing on Discord even though I am in-game on the server the report was sent in. Furthermore, the GUI showing incorrect report data seemed to be somewhat fixed. It takes around 5-10 seconds to change to the proper data in the GUI. The link below shows what the GUI shows when the report is first opened versus 10 seconds later.

https://imgur.com/a/0c5brxV

**Comment by MrTigreroux** [comment]
I would need you to do another "log record" for me please.
I would need you to start your server (with the logs.config file in TigerReports folder), join it, create a report (`/report <user> <reason>`), open that report (with `/reports <id of the created report>` that you can see putting your mouse on the alert message in the chat), change its status (from "Waiting") to `"In progress"`, close the menu, wait 10 seconds then stop your server.
Then send me all the logs starting from "[TigerReports] Enabling..." to "[TigerReports] Disabling...", but also a screenshot of the alert message of the report your created in your Discord channel.

**Comment by nicholasveronico** [comment]
Here are the logs: https://mcpaste.io/0689f2b12d7e623f

This screenshot was taken after the server was shut down: https://imgur.com/a/3FsXUlb

**Comment by MrTigreroux** [comment]
Thank you for your logs, I think that I found the problem (a simple forgotten "&"...) and fixed it in the new [version 1.6.6](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=455534) of TigerReportsSupports.
Don't forget to update TigerReports to the new [version 5.0.11](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455533).

**Comment by nicholasveronico** [comment]
The Discord message does not send with the new TigerReportSupports and TigerReports. This was the error: https://www.toptal.com/developers/hastebin/ipapefudow.properties

**Comment by MrTigreroux** [comment]
Ok I think that I finally found the issue (TigerReportsSupports was loaded before TigerReports was completly loaded) and fixed it in the new verions [5.0.12](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455606) of TigerReports and [1.6.7](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=455607) of TigerReportsSupports.
Thank you for reporting it !

**Comment by MrTigreroux** [comment]
It should be fixed with the new version [5.0.13](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455632) of TigerReports and [1.6.8](https://www.spigotmc.org/resources/tigerreportssupports.54612/update?update=455633) of TigerReportsSupports.
Thank you again for reporting the issue and for your logs which helped me a lot.

**Comment by nicholasveronico** [comment]
No problem! That did fix the issue for the Discord report statuses. I noticed another error related to the data section in the GUI. It errors whenever I right-click or left-click the data book. The data book also shows nothing in the lore (screenshot below)

https://www.toptal.com/developers/hastebin/monewekeda.properties
https://i.imgur.com/Ej2hb9p.png

**Comment by MrTigreroux** [comment]
Thank you for reporting it, it should be fixed in the new [version 5.0.14](https://www.spigotmc.org/resources/tigerreports.25773/update?update=455700)

**Comment by MrTigreroux** [comment]
No problem :)
